package com.s1155772.webshop.utils;

import com.s1155772.webshop.dao.*;
import com.s1155772.webshop.models.*;
import org.springframework.context.event.ContextRefreshedEvent;
import org.springframework.context.event.EventListener;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Component;

@Component
public class Seeder {
    private ProductRepository productRepository;

    private BrandRepository brandRepository;

    private CategoryRepository categoryRepository;

    private BestellingRepository bestellingRepository;

    private BestellingProductRepository bestellingProductRepository;



    private UserRepository userRepository;

    public Seeder(ProductRepository productRepository, BrandRepository brandRepository, CategoryRepository categoryRepository, BestellingRepository bestellingRepository, BestellingProductRepository bestellingProductRepository, UserRepository userRepository) {
        this.productRepository = productRepository;
        this.brandRepository = brandRepository;
        this.categoryRepository = categoryRepository;
        this.bestellingRepository = bestellingRepository;
        this.bestellingProductRepository = bestellingProductRepository;
        this.userRepository = userRepository;
    }

    @EventListener
    public void Seed(ContextRefreshedEvent event){
//        CustomUser customUser = new CustomUser();
//        customUser.setEmail("user@mail.com");
//        customUser.setPassword(new BCryptPasswordEncoder().encode("hallo"));
//        customUser.setVoornaam("Jasper");
//        userRepository.save(customUser);


        Categorie videokaarten = new Categorie("Videokaarten");
        Categorie processoren = new Categorie("Processoren");
        Categorie moederborden = new Categorie("Moederborden");
        this.categoryRepository.save(videokaarten);
        this.categoryRepository.save(processoren);
        this.categoryRepository.save(moederborden);

        Brand Asus = new Brand("Asus", "https://icon-icons.com/icons2/3911/PNG/512/asus_logo_icon_247542.png");
        Brand MSI = new Brand("MSI", "https://cdn.iconscout.com/icon/free/png-256/free-msi-1-286075.png");
        Brand INNO3D = new Brand("INNO3D", "https://images.seeklogo.com/logo-png/38/1/inno3d-logo-png_seeklogo-386197.png");
        Brand Gigabyte = new Brand("Gigabyte", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzXWXPZo00D9OsewodWmom-B7woZ3OT_EN1Q&s");
        Brand AMD = new Brand("AMD", "https://cdn.freebiesupply.com/logos/large/2x/amd-logo-png-transparent.png");
        this.brandRepository.save(Asus);
        this.brandRepository.save(MSI);
        this.brandRepository.save(INNO3D);
        this.brandRepository.save(Gigabyte);
        this.brandRepository.save(AMD);

        Product product = new Product("ASUS GeForce RTX 4070 DUAL-RTX 4070-O12G-EVO", 244000, Asus, videokaarten, 699, "De ASUS GeForce RTX 4070 DUAL-RTX 4070-O12G-EVO is een krachtige videokaart die ontworpen is voor veeleisende gaming en creatieve toepassingen. Met een GeForce RTX 4070 GPU, 12 GB GDDR6X-geheugen en 5888 CUDA-cores, biedt deze kaart uitstekende prestaties en ondersteuning voor geavanceerde grafische technologieën zoals DLSS 3. De hoge GPU-snelheden tot 2550 MHz zorgen voor soepele en gedetailleerde beeldweergave, waardoor gebruikers kunnen genieten van een immersieve gaming-ervaring of productieve creatieve workflows.", "The ASUS GeForce RTX 4070 DUAL-RTX 4070-O12G-EVO is a powerful graphics card designed for demanding gaming and creative applications. Featuring a GeForce RTX 4070 GPU, 12GB of GDDR6X memory, and 5888 CUDA cores, this card provides excellent performance and support for advanced graphics technologies like DLSS 3. Fast GPU speeds of up to 2550MHz ensure smooth and detailed image rendering, allowing you to enjoy immersive gaming experiences or productive creative workflows.", "https://www.megekko.nl/productimg/1104777/mini/1_ASUS-GeForce-RTX-4070-DUAL-RTX-4070-O12G-EVO-Videokaart.jpg");
        Product product2 = new Product("INNO3D GeForce RTX 5090 X3 32GB", 215000, INNO3D, videokaarten, 3899, "De INNO3D GeForce RTX 5090 X3 32GB Videokaart is een krachtige grafische kaart ontworpen voor de meest veeleisende pc-gebruikers. Met een geheugen van 32 GB GDDR7, een GPU-snelheid van maximaal 2467 MHz en 21760 CUDA-cores, biedt deze videokaart uitstekende prestaties voor veeleisende toepassingen zoals gamen, video-editing en GPU-accelerated computing. De kaart ondersteunt de nieuwste DLSS 4-technologie, waardoor gebruikers de beste beeldkwaliteit en prestaties kunnen ervaren.", "The INNO3D GeForce RTX 5090 X3 32GB Video Card is a powerful graphics card designed for the most demanding PC users. With 32GB GDDR7 memory, a GPU speed of up to 2467MHz and 21760 CUDA cores, this video card offers excellent performance for demanding applications such as gaming, video editing and GPU-accelerated computing. The card supports the latest DLSS 4 technology, allowing users to experience the best image quality and performance.", "https://www.megekko.nl/productimg/199615/mini/1_INNO3D-GeForce-RTX-5090-X3-32GB-Videokaart.jpg");
        Product product3 = new Product("MSI GeForce RTX 5070 Ti 16G VANGUARD SOC LAUNCH EDITION", 290000, MSI, videokaarten, 1329, "De MSI GeForce RTX 5070 Ti 16G VANGUARD SOC LAUNCH EDITION is een krachtige videokaart die gamers en creatieve professionals een hoogwaardige grafische prestatie biedt. Met 16 GB GDDR7-geheugen, een GPU-snelheid tot 2602 MHz en 8960 CUDA-cores kan deze videokaart veeleisende taken aan. De DLSS 4-technologie en RGB-verlichting maken deze videokaart tot een aantrekkelijke keuze voor liefhebbers van toonaangevende grafische prestaties.", "The MSI GeForce RTX 5070 Ti 16G VANGUARD SOC LAUNCH EDITION is a powerful graphics card that offers gamers and creative professionals high-end graphics performance. With 16GB of GDDR7 memory, a GPU speed of up to 2602MHz and 8960 CUDA cores, this graphics card can handle demanding tasks. The DLSS 4 technology and RGB lighting make this graphics card an attractive choice for enthusiasts of leading graphics performance.", "https://www.megekko.nl/productimg/967789/mini/1_MSI-GeForce-RTX-5070-Ti-16G-VANGUARD-SOC-LAUNCH-EDITION-Videokaart.jpg");
        Product product4 = new Product("MSI GeForce RTX 5080 16G VANGUARD SOC LAUNCH EDITION", 300000, MSI, videokaarten, 1500, "De MSI GeForce RTX 5080 16G VANGUARD SOC LAUNCH EDITION is een krachtige videokaart die is uitgerust met de nieuwste NVIDIA GeForce RTX 5080-graphics engine. Met 16 GB GDDR7-videogeheugen, een maximale GPU-snelheid van 2745 MHz en 10.752 CUDA-cores biedt deze videokaart uitstekende prestaties voor veeleisende gaming en content creation. Daarnaast ondersteunt deze videokaart de nieuwste DLSS 4-technologie voor verbeterde beeldkwaliteit en efficiëntie. De LED-verlichting geeft de kaart een stijlvolle uitstraling.", "The MSI GeForce RTX 5080 16G VANGUARD SOC LAUNCH EDITION is a powerful graphics card equipped with the latest NVIDIA GeForce RTX 5080 graphics engine. With 16 GB of GDDR7 video memory, a maximum GPU speed of 2745 MHz and 10,752 CUDA cores, this graphics card offers excellent performance for demanding gaming and content creation. In addition, this graphics card supports the latest DLSS 4 technology for improved image quality and efficiency. The LED lighting gives the card a stylish look.", "https://www.megekko.nl/productimg/967246/mini/1_MSI-GeForce-RTX-5080-16G-VANGUARD-SOC-LAUNCH-EDITION-Videokaart.jpg");
        Product product5 = new Product("ASUS Geforce RTX 4060 DUAL-RTX 4060-O8G-EVO", 288000, Asus, videokaarten, 349, "De ASUS Geforce RTX 4060 DUAL-RTX 4060-O8G-EVO is een krachtige videokaart die profiteert van de nieuwste NVIDIA GeForce RTX 4060-architectuur. Met 8 GB GDDR6-videogeheugen en snelheden tot 2535/2505 MHz biedt deze kaart uitstekende prestaties voor een breed scala aan gaming- en creatieve toepassingen. De 3072 CUDA-cores, gecombineerd met ondersteuning voor DLSS 3, maken van deze videokaart een aantrekkelijke keuze voor gebruikers op zoek naar een hoogwaardige grafische ervaring.", "The ASUS Geforce RTX 4060 DUAL-RTX 4060-O8G-EVO is a powerful graphics card that takes advantage of the latest NVIDIA GeForce RTX 4060 architecture. With 8GB of GDDR6 video memory and speeds of up to 2535/2505 MHz, this card provides excellent performance for a wide range of gaming and creative applications. Its 3072 CUDA cores, combined with support for DLSS 3, make this graphics card a compelling choice for users seeking a high-end graphics experience." ,"https://www.megekko.nl/productimg/1111046/mini/1_ASUS-Geforce-RTX-4060-DUAL-RTX-4060-O8G-EVO-Videokaart.jpg");


        Product product6 = new Product("AMD Ryzen 7 9800X3D", 315000, AMD, processoren, 574, "De AMD Ryzen 7 9800X3D is een krachtige 8-core processor in de Socket AM5-serie. Met een standaardkloksnelheid van 4.70 GHz en een turbokloksnelheid tot 5.20 GHz biedt deze processor uitstekende prestaties voor gaming en veeleisende workloads. De processor is uitgerust met AMD Radeon Graphics, maar wordt niet geleverd met een koeler. Dit maakt het een aantrekkelijke keuze voor pc-bouwers die op zoek zijn naar een flexibele en efficiënte processor voor hun nieuwe AM5-systeem.", "The AMD Ryzen 7 9800X3D is a powerful 8-core processor in the Socket AM5 series. With a base clock speed of 4.70 GHz and a turbo clock speed of up to 5.20 GHz, this processor offers excellent performance for gaming and demanding workloads. The processor is equipped with AMD Radeon Graphics, but does not come with a cooler. This makes it an attractive choice for PC builders looking for a flexible and efficient processor for their new AM5 system.", "https://www.megekko.nl/productimg/1752769/mini/1_AMD-Ryzen-7-9800X3D-Processor.jpg");
        Product product7 = new Product("AMD Ryzen 7 9700X", 928000, AMD, processoren, 355, "De AMD Ryzen 7 9700X is een krachtige processor in de Socket AM5-serie. Met 8 cores en een basiskloksnelheid van 3,80 GHz die kan worden opgevoerd tot 5,50 GHz, biedt deze processor uitstekende prestaties voor veeleisende taken. De processor ondersteunt AMD Radeon Graphics voor grafische taken, maar wordt geleverd zonder een eigen koeler. Deze AMD Ryzen 7-processor is een goede keuze voor gebruikers die op zoek zijn naar een robuuste en efficiënte processor voor hun desktop-pc.", "The AMD Ryzen 7 9700X is a powerful processor in the Socket AM5 series. With 8 cores and a base clock speed of 3.80 GHz that can be boosted up to 5.50 GHz, this processor offers excellent performance for demanding tasks. The processor supports AMD Radeon Graphics for graphical tasks, but does not come with its own cooler. This AMD Ryzen 7 processor is a good choice for users looking for a robust and efficient processor for their desktop PC.", "https://www.megekko.nl/productimg/295029/mini/1_AMD-Ryzen-7-9700X-Processor.jpg");
        Product product8 = new Product("AMD Ryzen 5 7600", 756000, AMD, processoren, 209, "De AMD Ryzen 5 7600 is een krachtige 6-core processor met een basiskloksnelheid van 3,80 GHz en een turbokloksnelheid tot 5,10 GHz. Dankzij de nieuwe AM5-socket en de geïntegreerde AMD Radeon Graphics biedt deze processor een uitstekende prestatie voor een breed scala aan toepassingen. Met de meegeleverde koeler is deze processor klaar voor gebruik.", "The AMD Ryzen 5 7600 is a powerful 6-core processor with a base clock speed of 3.80 GHz and a turbo clock speed of up to 5.10 GHz. Thanks to the new AM5 socket and the integrated AMD Radeon Graphics, this processor offers excellent performance for a wide range of applications. With the included cooler, this processor is ready for use.", "https://www.megekko.nl/productimg/294942/mini/1_AMD-Ryzen-5-7600-Processor.jpg");
        Product product9 = new Product("AMD Ryzen 7 8700G", 346000, AMD, processoren, 275, "De AMD Ryzen 7 8700G processor biedt een krachtige 8-cores CPU met een basiskloksnelheid van 4,20 GHz en een turbocloksnelheid tot 5,10 GHz. Deze processor is uitgerust met de geïntegreerde AMD Radeon 780M grafische eenheid, waardoor hij geschikt is voor zowel veeleisende toepassingen als lichtere taken. De Ryzen 7 8700G is ontworpen voor socket AM5 en wordt geleverd met een bijbehorende koeler, waardoor hij een veelzijdige en prestatiegerichte keuze kan zijn voor desktopcomputers.", "The AMD Ryzen 7 8700G processor offers a powerful 8-core CPU with a base clock speed of 4.20 GHz and a turbo clock speed of up to 5.10 GHz. This processor is equipped with the integrated AMD Radeon 780M graphics unit, making it suitable for both demanding applications and lighter tasks. The Ryzen 7 8700G is designed for socket AM5 and comes with a matching cooler, making it a versatile and performance-oriented choice for desktop computers.", "https://www.megekko.nl/productimg/261317/mini/1_AMD-Ryzen-7-8700G-Processor.jpg");
        Product product10 = new Product("AMD Ryzen 7 8700F", 723000, AMD, processoren, 249, "De AMD Ryzen 7 8700F is een krachtige processor uit de Ryzen 7-serie, ontworpen voor socket AM5. Met een basiskloktempo van 4,10 GHz en een turbosnelheid tot 5,00 GHz, biedt deze 8-core CPU uitstekende prestaties voor veeleisende taken. Hoewel er geen geïntegreerde grafische functies aanwezig zijn, wordt de processor geleverd met een bijpassende koeler voor een complete setup. Deze Ryzen 7-processor kan een waardevolle toevoeging zijn aan uw high-end computersysteem.", "The AMD Ryzen 7 8700F is a powerful processor from the Ryzen 7 series, designed for socket AM5. With a base clock of 4.10 GHz and a turbo speed of up to 5.00 GHz, this 8-core CPU offers excellent performance for demanding tasks. Although there are no integrated graphics features, the processor comes with a matching cooler for a complete setup. This Ryzen 7 processor can be a valuable addition to your high-end computer system.", "https://www.megekko.nl/productimg/261325/mini/1_AMD-Ryzen-7-8700F-Processor.jpg");


        Product product11 = new Product("MSI B760 GAMING PLUS WIFI", 388000, MSI, moederborden, 164, "Het MSI B760 GAMING PLUS WIFI moederbord is een krachtig en veelzijdig Intel Socket 1700 moederbord dat is uitgerust met de Intel B760-chipset. Met 4 geheugenslots en ondersteuning voor maximaal 192 GB DDR5-geheugen biedt het uitstekende prestaties. Daarnaast is het moederbord voorzien van Wi-Fi-connectiviteit en 2 M.2-slots voor snelle SSD-opslag. Het ATX-formaat maakt het geschikt voor diverse pc-configuraties.", "The MSI B760 GAMING PLUS WIFI motherboard is a powerful and versatile Intel Socket 1700 motherboard that is equipped with the Intel B760 chipset. With 4 memory slots and support for up to 192GB DDR5 memory, it offers excellent performance. In addition, the motherboard is equipped with Wi-Fi connectivity and 2 M.2 slots for fast SSD storage. The ATX format makes it suitable for various PC configurations.", "https://www.megekko.nl/productimg/1080950/mini/1_MSI-B760-GAMING-PLUS-WIFI-moederbord.jpg");
        Product product12 = new Product("ASUS ROG STRIX Z790-H GAMING WIFI", 4992000, Asus, moederborden, 245, "Het ASUS ROG STRIX Z790-H GAMING WIFI moederbord is een high-end ATX-formaat moederbord voor Intel Socket 1700 processoren. Het biedt ondersteuning voor maximaal 128GB DDR5-geheugen verspreid over 4 geheugenslots. Met één PCI-E 5.0 x16-slot en vier M.2-slots is dit moederbord uitgerust voor krachtige gaming-pc's. Daarnaast beschikt het over ingebouwde Wi-Fi-connectiviteit, waardoor je gemakkelijk kunt profiteren van draadloze internetverbindingen.", "The ASUS ROG STRIX Z790-H GAMING WIFI motherboard is a high-end ATX-sized motherboard for Intel Socket 1700 processors. It supports up to 128GB of DDR5 memory across 4 memory slots. With one PCI-E 5.0 x16 slot and four M.2 slots, this motherboard is equipped for powerful gaming PCs. In addition, it features built-in Wi-Fi connectivity, allowing you to easily enjoy wireless internet connections.", "https://www.megekko.nl/productimg/1075982/mini/1_ASUS-ROG-STRIX-Z790-H-GAMING-WIFI-moederbord.jpg");
        Product product13 = new Product("MSI PRO B760M-P DDR4", 273000, MSI, moederborden, 99, "Het MSI PRO B760M-P DDR4 moederbord is een krachtig Micro-ATX-moederbord voor de Intel Socket 1700-chipset. Het biedt vier geheugenslots voor maximaal 128 GB DDR4-geheugen, evenals twee M.2-slots voor snelle opslagoplossingen. Dit moederbord is ontworpen voor een breed scala aan toepassingen, van gaming tot professioneel gebruik, en biedt een solide basis voor uw pc-bouw.", "The MSI PRO B760M-P DDR4 motherboard is a powerful Micro-ATX motherboard for the Intel Socket 1700 chipset. It offers four memory slots for up to 128GB of DDR4 memory, as well as two M.2 slots for high-speed storage solutions. Designed for a wide range of applications from gaming to professional use, this motherboard provides a solid foundation for your PC build.", "https://www.megekko.nl/productimg/1074833/mini/1_MSI-PRO-B760M-P-DDR4-moederbord.jpg");
        Product product14 = new Product("MSI MAG Z790 TOMAHAWK WIFI", 383000, MSI, moederborden, 259, "Het MSI MAG Z790 TOMAHAWK WIFI is een krachtig ATX-moederbord voor Intel Socket 1700-processors. Met de Intel Z790-chipset, ondersteuning voor maximaal 128 GB DDR5-geheugen en 4 M.2-sleuven biedt dit moederbord de nodige prestaties en flexibiliteit voor veeleisende desktopcomputers. Daarnaast is het uitgerust met Wi-Fi en een enkele PCI-E 5.0 x16-sleuf voor geavanceerde grafische kaarten. Dit MSI-moederbord is een solide keuze voor enthousiastelingen die op zoek zijn naar een robuust en veelzijdig Intel Socket 1700-platform.", "The MSI MAG Z790 TOMAHAWK WIFI is a powerful ATX motherboard for Intel Socket 1700 processors. With the Intel Z790 chipset, support for up to 128GB DDR5 memory and 4 M.2 slots, this motherboard offers the necessary performance and flexibility for demanding desktop computers. In addition, it is equipped with Wi-Fi and a single PCI-E 5.0 x16 slot for advanced graphics cards.", "https://www.megekko.nl/productimg/1070478/mini/1_MSI-MAG-Z790-TOMAHAWK-WIFI-moederbord.jpg");
        Product product15 = new Product("Gigabyte B760 GAMING X", 222000, Gigabyte, moederborden, 388, "Het Gigabyte B760 GAMING X moederbord is een krachtig Intel Socket 1700 moederbord dat is ontworpen voor gaming en high-performance toepassingen. Met een ATX form factor, 4 geheugenslots voor maximaal 256 GB DDR5 geheugen en 3 M.2 slots, biedt dit moederbord de flexibiliteit en capaciteit die gebruikers nodig hebben voor hun high-end systemen. Het Intel B760 chipset zorgt voor een betrouwbare en efficiënte prestatie, waardoor dit moederbord een geweldige keuze is voor zowel gaming als professioneel gebruik.", "The Gigabyte B760 GAMING X motherboard is a powerful Intel Socket 1700 motherboard designed for gaming and high-performance applications. Featuring an ATX form factor, 4 memory slots for up to 256GB DDR5 memory and 3 M.2 slots, this motherboard offers the flexibility and capacity users need for their high-end systems.", "https://www.megekko.nl/productimg/1076241/mini/1_Gigabyte-B760-GAMING-X-moederbord.jpg");

        Product product16 = new Product("Gigabyte Radeon RX 7800 XT GAMING OC 16G", 90000, Gigabyte, videokaarten, 519, "De Gigabyte Radeon RX 7800 XT GAMING OC 16G is een krachtige videokaart voor veeleisende gamers. Met zijn 16 GB GDDR6-geheugen, 3840 stream processors en een maximale GPU-snelheid van 2565 MHz biedt deze kaart uitstekende prestaties voor de meeste hedendaagse games. De RGB-verlichting geeft een stijlvol accent aan je gaming setup. Of deze kaart geschikt is voor jouw specifieke behoeften, is afhankelijk van je individuele vereisten.", "The Gigabyte Radeon RX 7800 XT GAMING OC 16G is a powerful graphics card for demanding gamers. With its 16 GB GDDR6 memory, 3840 stream processors and a maximum GPU speed of 2565 MHz, this card offers excellent performance for most of today's games. The RGB lighting gives a stylish accent to your gaming setup. Whether this card is suitable for your specific needs depends on your individual requirements.", "https://www.megekko.nl/productimg/310921/mini/1_Gigabyte-Radeon-RX-7800-XT-GAMING-OC-16G-Videokaart.jpg");
        Product product17 = new Product("ASUS Prime AMD Radeon RX 9070 XT Gaming OC 16GB", 89374, Asus, videokaarten, 889, "De ASUS Prime AMD Radeon RX 9070 XT Gaming OC 16GB is een krachtige videokaart, ontworpen voor veeleisende gamers en creatieve professionals. Met de Radeon RX 9070 XT-GPU, 16 GB GDDR6-geheugen en een maximale kloksnelheid van 3030 MHz, biedt deze kaart uitstekende prestaties voor een breed scala aan toepassingen, van high-end gaming tot video-editing en 3D-rendering. De 4096 stream processors garanderen een soepele en gedetailleerde visuele ervaring. Deze ASUS-videokaart is een aantrekkelijke keuze voor gebruikers die op zoek zijn naar een geoptimaliseerde AMD-oplossing voor hun systeem.", "The ASUS Prime AMD Radeon RX 9070 XT Gaming OC 16GB is a powerful graphics card designed for demanding gamers and creative professionals. Featuring the Radeon RX 9070 XT GPU, 16GB of GDDR6 memory, and a maximum clock speed of 3,030 MHz, this card provides excellent performance for a wide range of applications, from high-end gaming to video editing and 3D rendering. Its 4,096 stream processors ensure a smooth and detailed visual experience. This ASUS graphics card is a compelling choice for users looking for an optimized AMD solution for their system.", "https://www.megekko.nl/productimg/1699548/mini/1_ASUS-Prime-AMD-Radeon-RX-9070-XT-Gaming-OC-16GB-Videokaart.jpg");
        Product product18 = new Product("Gigabyte Radeon RX 7700 XT GAMING OC 12G", 389474, Gigabyte, videokaarten, 459, "De Gigabyte Radeon RX 7700 XT GAMING OC 12G is een krachtige videokaart die is uitgerust met 12 GB GDDR6-geheugen en een maximale GPU-kloksnelheid van 2599 MHz. Met 3456 stream processors biedt deze kaart een indrukwekkende prestatie voor gamers en creatievelingen. De RGB-verlichting geeft een mooi accent aan de kaart in je PC-configuratie.", "The Gigabyte Radeon RX 7700 XT GAMING OC 12G is a powerful graphics card equipped with 12GB of GDDR6 memory and a maximum GPU clock speed of 2599MHz. With 3456 stream processors, this card offers impressive performance for gamers and creatives. The RGB lighting gives a nice accent to the card in your PC setup.", "https://www.megekko.nl/productimg/310922/mini/1_Gigabyte-Radeon-RX-7700-XT-GAMING-OC-12G-Videokaart.jpg");
        Product product19 = new Product("Gigabyte Radeon RX 9070 GAMING OC 16GB", 123123, Gigabyte, videokaarten, 699, "De Gigabyte Radeon RX 9070 GAMING OC 16GB Videokaart is een krachtige AMD-GPU met 16 GB GDDR6-geheugen en een maximale snelheid van 2700 MHz. Met 3584 stream processors biedt deze videokaart robuuste prestaties voor veeleisende gaming-ervaringen en grafisch intensieve taken. Gebruikers kunnen profiteren van de geavanceerde functionaliteit en het effectieve koelsysteem van deze Gigabyte-oplossing.", "The Gigabyte Radeon RX 9070 GAMING OC 16GB Video Card is a powerful AMD GPU with 16GB of GDDR6 memory and a maximum speed of 2700MHz. With 3584 stream processors, this video card offers robust performance for demanding gaming experiences and graphically intensive tasks. Users can benefit from the advanced functionality and effective cooling system of this Gigabyte solution.", "https://www.megekko.nl/productimg/1725847/mini/1_Gigabyte-Radeon-RX-9070-GAMING-OC-16GB-Videokaart.jpg");
        Product product20 = new Product("Gigabyte Radeon RX 7600 XT 16GB GAMING OC", 46648, Gigabyte, videokaarten, 379, "De Gigabyte Radeon RX 7600 XT 16GB GAMING OC Videokaart is een krachtige AMD-videokaart met 16 GB GDDR6-geheugen en een GPU-snelheid tot 2810 MHz. Met 2048 stream processors biedt deze kaart uitstekende prestaties voor grafisch veeleisende taken, ondersteund door LED-verlichting voor een stijlvolle PC-look.", "The Gigabyte Radeon RX 7600 XT 16GB GAMING OC Video Card is a powerful AMD video card with 16GB of GDDR6 memory and a GPU speed of up to 2810 MHz. With 2048 stream processors, this card offers excellent performance for graphically demanding tasks, supported by LED lighting for a stylish PC look.", "https://www.megekko.nl/productimg/958604/mini/1_Gigabyte-Radeon-RX-7600-XT-16GB-GAMING-OC-Videokaart.jpg");

        Product product21 = new Product("AMD Ryzen Threadripper 7980X", 827, AMD, processoren, 4799, "De AMD Ryzen Threadripper 7980X is een krachtige Socket sTRX5 processor met 64 cores en 128 threads. Met een basiskloksnelheid van 3,20 GHz en een Turbo Boost tot 5,10 GHz, biedt deze CPU meer dan genoeg vermogen voor veeleisende taken zoals content creation, 3D-rendering en dataverwerking", "The AMD Ryzen Threadripper 7980X is a powerful Socket sTRX5 processor with 64 cores and 128 threads. With a base clock speed of 3.20 GHz and a Turbo Boost of up to 5.10 GHz, this CPU offers more than enough power for demanding tasks such as content creation, 3D rendering and data processing", "https://www.megekko.nl/productimg/999631/mini/1_AMD-Ryzen-Threadripper-7980X.jpg");
        Product product22 = new Product("AMD Ryzen Threadripper 7960X", 62, AMD, processoren, 1349, "De AMD Ryzen Threadripper 7960X is een krachtige 24-core, 48-thread processor voor veeleisende werklasten. Met een basiskloksnelheid van 4,20 GHz en een Turbo Boost tot 5,30 GHz, biedt deze sTRX5-socket processor uitzonderlijke prestaties voor professionele toepassingen zoals 3D-rendering, video-editing en gegevensanalyse", "The AMD Ryzen Threadripper 7960X is a powerful 24-core, 48-thread processor for demanding workloads. With a base clock speed of 4.20 GHz and a Turbo Boost of up to 5.30 GHz, this sTRX5-socket processor offers exceptional performance for professional applications such as 3D rendering, video editing, and data analysis.", "https://www.megekko.nl/productimg/999629/mini/1_AMD-Ryzen-Threadripper-7960X.jpg");
        Product product23 = new Product("AMD Ryzen Threadripper PRO 7985WX", 83, AMD, processoren, 8203, "De AMD Ryzen Threadripper PRO 7985WX is een krachtige processor uit de AMD Ryzen PRO-serie die is ontworpen voor veeleisende werkbelastingen. Met 64 cores, 128 threads en een Turbo Boost-snelheid tot 5,10 GHz biedt deze processor uitstekende prestaties voor professionals die behoefte hebben aan geavanceerde multitasking en snelle dataverwerking.", "The AMD Ryzen Threadripper PRO 7985WX is a powerful processor from the AMD Ryzen PRO series designed for demanding workloads. With 64 cores, 128 threads and a Turbo Boost speed of up to 5.10 GHz, this processor offers excellent performance for professionals who need advanced multitasking and fast data processing.", "https://www.megekko.nl/productimg/1099350/mini/1_AMD-Ryzen-Threadripper-PRO-7985WX.jpg");
        Product product24 = new Product("AMD Ryzen Threadripper PRO 7965WX", 92, AMD, processoren, 3180, "De AMD Ryzen Threadripper PRO 7965WX is een krachtige processor uit de AMD Ryzen PRO-serie, ontworpen voor high-end workstations en professionele toepassingen. Met 24 cores, 48 threads, een basiskloksnelheid van 4,20 GHz en een Turbo Boost tot 5,30 GHz, biedt deze processor uitstekende prestaties voor veeleisende taken zoals 3D-modellering, video-editing en dataverwerking.", "The AMD Ryzen Threadripper PRO 7965WX is a powerful processor from the AMD Ryzen PRO series, designed for high-end workstations and professional applications. With 24 cores, 48 threads, a base clock speed of 4.20 GHz and a Turbo Boost of up to 5.30 GHz, this processor offers excellent performance for demanding tasks such as 3D modeling, video editing, and data processing.", "https://www.megekko.nl/productimg/999680/mini/1_AMD-Ryzen-Threadripper-PRO-7965WX.jpg");
        Product product25 = new Product("AMD Ryzen Threadripper PRO 7995WX", 5, AMD, processoren, 11153, "De AMD Ryzen Threadripper PRO 7995WX is een krachtige socket sTRX5 processor met 96 cores en 192 threads. Met een basiskloksnelheid van 2,50 GHz en een turbokloksnelheid tot 5,10 GHz biedt deze processor uitzonderlijke prestaties voor veeleisende workloads.", "De AMD Ryzen Threadripper PRO 7995WX is een krachtige socket sTRX5 processor met 96 cores en 192 threads. Met een basiskloksnelheid van 2,50 GHz en een turbokloksnelheid tot 5,10 GHz biedt deze processor uitzonderlijke prestaties voor veeleisende workloads.", "https://www.megekko.nl/productimg/999632/mini/1_AMD-Ryzen-Threadripper-PRO-7995WX.jpg");

        Product product26 = new Product("ASUS ROG STRIX B650E-F GAMING WIFI", 28477, Asus, moederborden, 229, "Het ASUS ROG STRIX B650E-GAMING WIFI moederbord biedt een krachtige AMD Socket AM5 platform met de B650 chipset. Dit ATX-formaat moederbord heeft 4 DDR5 geheugenslots met ondersteuning voor tot 192GB geheugen.", "The ASUS ROG STRIX B650E-GAMING WIFI motherboard offers a powerful AMD Socket AM5 platform with the B650 chipset. This ATX format motherboard has 4 DDR5 memory slots with support for up to 192GB of memory.", "https://www.megekko.nl/productimg/1070488/mini/1_ASUS-ROG-STRIX-B650E-F-GAMING-WIFI-moederbord.jpg");
        Product product27 = new Product("Gigabyte B650 EAGLE AX", 23737, Gigabyte, moederborden, 159, "Het Gigabyte B650 EAGLE AX moederbord is een krachtig AMD Socket AM5-model dat ondersteuning biedt voor DDR5-geheugen met een maximale capaciteit van 256 GB. Met zijn ATX-form factor, 4 geheugenslots, 1 PCI-E 4.0 x16-slot en 3 M.2-slots is dit moederbord geschikt voor een brede range aan high-end pc-configuraties.", "The Gigabyte B650 EAGLE AX motherboard is a powerful AMD Socket AM5 model that supports DDR5 memory with a maximum capacity of 256GB. With its ATX form factor, 4 memory slots, 1 PCI-E 4.0 x16 slot and 3 M.2 slots, this motherboard is suitable for a wide range of high-end PC configurations.", "https://www.megekko.nl/productimg/1108090/mini/1_Gigabyte-B650-EAGLE-AX-moederbord.jpg");
        Product product28 = new Product("MSI MAG B850 TOMAHAWK MAX WIFI", 2837, MSI, moederborden, 269, "Het MSI MAG B850 TOMAHAWK MAX WIFI moederbord is een krachtig en veelzijdig AMD Socket AM5 model. Met zijn ATX-formaat, 4 DDR5-geheugenslots, PCI-E 5.0 en 4.0 x16 slots, en 4 M.2-sleuven biedt het uitstekende connectiviteit en uitbreidingsmogelijkheden.", "The MSI MAG B850 TOMAHAWK MAX WIFI motherboard is a powerful and versatile AMD Socket AM5 model. With its ATX format, 4 DDR5 memory slots, PCI-E 5.0 and 4.0 x16 slots, and 4 M.2 slots, it offers excellent connectivity and expandability.", "https://www.megekko.nl/productimg/1153384/mini/1_MSI-MAG-B850-TOMAHAWK-MAX-WIFI-moederbord.jpg");
        Product product29 = new Product("MSI MPG X870E CARBON WIFI", 228, MSI, moederborden, 479, "Het MSI MPG X870E CARBON WIFI moederbord is een krachtig AMD Socket AM5 moederbord dat is ontworpen voor hoogwaardige prestaties. Met zijn ATX-formaat, 4 geheugenslots voor maximaal 256 GB DDR5 RAM, 2 PCI-E 5.0 x16 en 1 PCI-E 4.0 x16 slot, samen met 4 M.2-slots, biedt dit moederbord uitstekende connectiviteit en uitbreidingsmogelijkheden.", "The MSI MPG X870E CARBON WIFI motherboard is a powerful AMD Socket AM5 motherboard designed for high-end performance. With its ATX form factor, 4 memory slots for up to 256GB DDR5 RAM, 2 PCI-E 5.0 x16 and 1 PCI-E 4.0 x16 slot, along with 4 M.2 slots, this motherboard offers excellent connectivity and expandability.", "https://www.megekko.nl/productimg/1148650/mini/1_MSI-MPG-X870E-CARBON-WIFI-moederbord.jpg");
        Product product30 = new Product("ASUS ROG STRIX B650-A GAMING WIFI", 288, Asus, moederborden, 229, "Het ASUS ROG STRIX B650-A GAMING WIFI moederbord is een krachtig AMD Socket AM5 model met een ATX-formaat. Het biedt 4 DDR5-geheugenslots met een totale capaciteit van 192 GB. Daarnaast heeft het 2 PCI-E 4.0 x16-slots en 2 PCI-E 4.0 x1-slots, evenals 3 M.2-sleuven.", "The ASUS ROG STRIX B650-A GAMING WIFI motherboard is a powerful AMD Socket AM5 model with an ATX form factor. It offers 4 DDR5 memory slots with a total capacity of 192 GB. Additionally, it has 2 PCI-E 4.0 x16 slots and 2 PCI-E 4.0 x1 slots, as well as 3 M.2 slots.", "https://www.megekko.nl/productimg/1070490/mini/1_ASUS-ROG-STRIX-B650-A-GAMING-WIFI-moederbord.jpg");

        this.productRepository.save(product29);
        this.productRepository.save(product23);
        this.productRepository.save(product17);
        this.productRepository.save(product5);
        this.productRepository.save(product14);
        this.productRepository.save(product26);
        this.productRepository.save(product7);
        this.productRepository.save(product21);
        this.productRepository.save(product19);
        this.productRepository.save(product);
        this.productRepository.save(product30);
        this.productRepository.save(product18);
        this.productRepository.save(product13);
        this.productRepository.save(product6);
        this.productRepository.save(product3);
        this.productRepository.save(product10);
        this.productRepository.save(product15);
        this.productRepository.save(product8);
        this.productRepository.save(product16);
        this.productRepository.save(product4);
        this.productRepository.save(product27);
        this.productRepository.save(product22);
        this.productRepository.save(product12);
        this.productRepository.save(product20);
        this.productRepository.save(product2);
        this.productRepository.save(product24);
        this.productRepository.save(product9);
        this.productRepository.save(product28);
        this.productRepository.save(product11);
        this.productRepository.save(product25);


    }

}
